# Quiz 8b

When you reach the rover, you discover that it's already in the process of rebooting! It's just waiting for someone to enter a BIOS password. The Elf responsible for the rover takes a Now you're ready to decode the image. The image is rendered by stacking the layers and aligning the pixels with the same positions in each layer. The digits indicate the color of the corresponding pixel: 0 is black, 1 is white, and 2 is transparent.

The layers are rendered with the first layer in front and the last layer in back. So, if a given position has a transparent pixel in the first and second layers, a black pixel in the third layer, and a white pixel in the fourth layer, the final image would have a black pixel at that position.

For example, given an image 2 pixels wide and 2 pixels tall, the image data 0222112222120000 corresponds to the following image layers:

Layer 1: 02
         22

Layer 2: 11
         22

Layer 3: 22
         12

Layer 4: 00
         00
Then, the full image can be found by determining the top visible pixel in each position:

The top-left pixel is black because the top layer is 0.
The top-right pixel is white because the top layer is 2 (transparent), but the second layer is 1.
The bottom-left pixel is white because the top two layers are 2, but the third layer is 1.
The bottom-right pixel is black because the only visible pixel in that position is 0 (from layer 4).
So, the final image looks like this:

01
10
What message is produced after decoding your image?

In [51]:
import sys
import numpy
numpy.set_printoptions(linewidth=sys.maxsize)

In [1]:
with open('8-input.txt', 'r') as input_file:
    input_data = input_file.read()
    input_data = input_data.strip()

In [25]:
def find_pixel_color(input_data, pixel, size_of_layer):
    no_of_layers = int(len(input_data) / size_of_layer)
    for layer in range(no_of_layers):
        pixel_value = input_data[pixel]
#         print(f">>>DEBUG: layer {layer} with pixel_value {pixel_value}")
        if pixel_value in ['0','1']:
            return int(pixel_value)
        else:
            pixel += size_of_layer

In [26]:
def build_visible_layer(input_data, wide, tall):
    size_of_layer = wide * tall
#     print(f">>>DEBUG: size of layer: {size_of_layer}")
    visible_pixels = []
    for pixel in range(size_of_layer):
        visible_pixels.append(find_pixel_color(input_data, pixel, size_of_layer))
    return visible_pixels

In [42]:
def build_picture(layer, wide, tall):
    picture_array = np.array([layer[(wide*x):(wide*x+wide)] for x in range(tall)])
    return picture_array

In [32]:
wide = 25
tall = 6

visible_layer_inline = build_visible_layer(input_data, wide, tall)

In [ ]:
print(f">>>DEBUG: visible layer: {visible_layer_inline}")

In [54]:
picture = build_picture(visible_layer_inline, wide, tall)
picture = picture * 88 # improve readability of result
picture = picture + 1 # improve readability of result
print(picture)

[[89  1  1 89  1 89 89 89  1  1 89  1  1 89  1 89 89 89 89  1 89 89 89  1  1]
 [89  1  1 89  1 89  1  1 89  1 89  1  1 89  1 89  1  1  1  1 89  1  1 89  1]
 [89  1  1 89  1 89 89 89  1  1 89  1  1 89  1 89 89 89  1  1 89  1  1 89  1]
 [89  1  1 89  1 89  1  1 89  1 89  1  1 89  1 89  1  1  1  1 89 89 89  1  1]
 [89  1  1 89  1 89  1  1 89  1 89  1  1 89  1 89  1  1  1  1 89  1  1  1  1]
 [ 1 89 89  1  1 89 89 89  1  1  1 89 89  1  1 89  1  1  1  1 89  1  1  1  1]]
